	.byte $00	; Unknown purpose

	.byte OBJ_BLOOPER, $10, $16
	.byte OBJ_BLOOPER, $24, $12
	.byte OBJ_WATERCURRENTDOWNARD, $3C, $11
	.byte OBJ_GREENCHEEP, $44, $15
	.byte OBJ_GREENCHEEP, $4C, $14
	.byte OBJ_GREENCHEEP, $56, $15
	.byte OBJ_GREENCHEEP, $5E, $13
	.byte OBJ_GREENCHEEP, $62, $16
	.byte OBJ_GREENCHEEP, $69, $16
	.byte OBJ_GREENCHEEP, $6D, $13
	.byte OBJ_GREENCHEEP, $71, $16
	.byte OBJ_GREENCHEEP, $7D, $12
	.byte OBJ_WATERCURRENTDOWNARD, $82, $12
	.byte OBJ_WATERCURRENTDOWNARD, $85, $11
	.byte OBJ_WATERCURRENTDOWNARD, $88, $12
	.byte OBJ_BLOOPER, $8C, $14
	.byte OBJ_WATERCURRENTUPWARD, $A1, $16
	.byte OBJ_WATERCURRENTUPWARD, $A3, $16
	.byte OBJ_GREENCHEEP, $B5, $12
	.byte $FF
