	.byte $00	; Unknown purpose

	.byte OBJ_CHECKPOINT, $17, $17
	.byte OBJ_REDTROOPA, $22, $0F
	.byte OBJ_GOOMBA, $30, $0F
	.byte OBJ_GOOMBA, $34, $0F
	.byte OBJ_OSCILLATING_V, $3F, $18
	.byte OBJ_FLYINGREDPARATROOPA, $55, $0F
	.byte OBJ_GOOMBA, $5A, $0F
	.byte OBJ_OSCILLATING_H, $64, $12
	.byte OBJ_OSCILLATING_H, $6B, $14
	.byte OBJ_REDTROOPA, $76, $11
	.byte OBJ_FLYINGREDPARATROOPA, $7F, $11
	.byte OBJ_REDTROOPA, $91, $18
	.byte OBJ_OSCILLATING_HS, $93, $12
	.byte OBJ_ENDLEVELCARD, $A7, $11
	.byte $FF
