	.byte $00	; Unknown purpose

	.byte OBJ_GREENPIRANHA, $0E, $16
	.byte OBJ_LAKITU, $14, $11
	.byte OBJ_GREENPIRANHA, $6A, $15
	.byte OBJ_REDTROOPA, $6A, $06
	.byte OBJ_GREENCHEEP, $71, $0A
	.byte OBJ_REDTROOPA, $72, $04
	.byte OBJ_ALTLEVELMOD, $76, $00
	.byte OBJ_REDTROOPA, $7A, $03
	.byte OBJ_ALTLEVELMOD, $80, $00
	.byte OBJ_GREENPIRANHA, $91, $17
	.byte OBJ_PARATROOPAGREENHOP, $BA, $06
	.byte OBJ_PARATROOPAGREENHOP, $BE, $05
	.byte OBJ_PARATROOPAGREENHOP, $C1, $06
	.byte OBJ_FLYINGREDPARATROOPA, $C6, $01
	.byte OBJ_REDTROOPA, $DD, $13
	.byte OBJ_ENDLEVELCARD, $E6, $11
	.byte $FF
