	.byte $00	; Unknown purpose

	.byte OBJ_CHECKPOINT, $1A, $06
	.byte OBJ_GOOMBA, $29, $06
	.byte OBJ_GOOMBA, $2B, $06
	.byte OBJ_GOOMBA, $2D, $06
	.byte OBJ_GREENPIRANHA, $54, $08
	.byte OBJ_GREENTROOPA, $58, $0A
	.byte OBJ_GREENPIRANHA, $5A, $04
	.byte OBJ_BUZZYBEATLE, $5D, $0A
	.byte OBJ_BUZZYBEATLE, $63, $0A
	.byte OBJ_GREENPIRANHA, $65, $08
	.byte OBJ_GREENTROOPA, $6F, $0A
	.byte OBJ_GREENTROOPA, $71, $0A
	.byte OBJ_GREENTROOPA, $92, $0A
	.byte OBJ_GREENPIRANHA, $99, $07
	.byte OBJ_BUZZYBEATLE, $A5, $07
	.byte OBJ_GREENTROOPA, $AE, $0A
	.byte OBJ_GREENTROOPA, $B0, $0A
	.byte OBJ_BUZZYBEATLE, $BE, $0A
	.byte $FF
