	.byte $00	; Unknown purpose

	.byte OBJ_OSCILLATING_V, $1C, $1A
	.byte OBJ_OSCILLATING_HS, $2A, $13
	.byte OBJ_OSCILLATING_HS, $2E, $15
	.byte OBJ_OSCILLATING_HS, $38, $13
	.byte OBJ_OSCILLATING_V, $3E, $19
	.byte OBJ_WOODENPLATUNSTABLE, $4B, $11
	.byte OBJ_WOODENPLATUNSTABLE, $51, $15
	.byte OBJ_WOODENPLATUNSTABLE, $55, $11
	.byte OBJ_WOODENPLATUNSTABLE, $59, $15
	.byte OBJ_VENUSFIRETRAP_CEIL, $7D, $02
	.byte OBJ_OSCILLATING_HS, $85, $13
	.byte OBJ_VENUSFIRETRAP_CEIL, $87, $02
	.byte OBJ_WOODENPLATUNSTABLE, $89, $14
	.byte OBJ_WOODENPLATUNSTABLE, $8D, $16
	.byte OBJ_CHECKPOINT, $91, $18
	.byte OBJ_WOODENPLATUNSTABLE, $99, $13
	.byte OBJ_WOODENPLATUNSTABLE, $9D, $15
	.byte OBJ_WOODENPLATUNSTABLE, $A1, $12
	.byte OBJ_WOODENPLATUNSTABLE, $A5, $13
	.byte OBJ_REDTROOPA, $B2, $11
	.byte OBJ_GOOMBA, $B6, $12
	.byte OBJ_GOOMBA, $B8, $12
	.byte OBJ_GOOMBA, $BA, $12
	.byte OBJ_OSCILLATING_V, $C0, $19
	.byte OBJ_FLYINGREDPARATROOPA, $D4, $11
	.byte OBJ_FLYINGGREENPARATROOPA, $DD, $12
	.byte OBJ_ENDLEVELCARD, $E7, $10
	.byte $FF
