	.byte $00	; Unknown purpose

	.byte OBJ_CHECKPOINT, $08, $0A
	.byte OBJ_CFIRE_BULLETBILL, $11, $09
	.byte OBJ_PARATROOPAGREENHOP, $1B, $0A
	.byte OBJ_CFIRE_BULLETBILL, $1F, $08
	.byte OBJ_GREENPIRANHA, $25, $07
	.byte OBJ_HAMMERBRO, $2F, $05
	.byte OBJ_HAMMERBRO, $31, $01
	.byte OBJ_CFIRE_BULLETBILL, $47, $09
	.byte OBJ_PARATROOPAGREENHOP, $4C, $0A
	.byte OBJ_HAMMERBRO, $6A, $05
	.byte OBJ_HAMMERBRO, $6D, $01
	.byte OBJ_GREENPIRANHA, $73, $07
	.byte OBJ_GREENTROOPA, $7D, $0A
	.byte OBJ_HAMMERBRO, $84, $09
	.byte OBJ_HAMMERBRO, $8E, $09
	.byte OBJ_GREENPIRANHA, $93, $08
	.byte OBJ_HAMMERBRO, $9B, $09
	.byte OBJ_HAMMERBRO, $A5, $09
	.byte OBJ_ENDLEVELCARD, $C9, $02
	.byte $FF
