	.byte $00	; Unknown purpose

	.byte OBJ_PODOBOO, $10, $14
	.byte OBJ_REDTROOPA, $18, $16
	.byte OBJ_PODOBOO, $1A, $14
	.byte OBJ_THWOMPDIAGONALDL, $24, $01
	.byte OBJ_THWOMPDIAGONALUL, $2E, $09
	.byte OBJ_ALTLEVELMOD, $3A, $00
	.byte OBJ_PODOBOO, $41, $03
	.byte OBJ_DRYBONES, $4B, $18
	.byte OBJ_DRYBONES, $4E, $18
	.byte OBJ_PODOBOO, $5B, $14
	.byte OBJ_PODOBOO, $5B, $03
	.byte OBJ_PODOBOO, $65, $14
	.byte OBJ_PODOBOO, $6B, $14
	.byte OBJ_CHECKPOINT, $7D, $16
	.byte OBJ_FIREJET_UPWARD, $84, $15
	.byte OBJ_FIREJET_UPWARD, $8A, $15
	.byte OBJ_FIREJET_UPWARD, $90, $15
	.byte OBJ_ALTLEVELMOD, $B6, $00
	.byte OBJ_GREENPIRANHA, $B6, $17
	.byte OBJ_WOODENPLATUNSTABLE, $C8, $1A
	.byte OBJ_THWOMPLEFTSLIDE, $E0, $15
	.byte $FF
