	.byte $00	; Unknown purpose

	.byte OBJ_SHYGUY_GREEN, $0E, $18
	.byte OBJ_SHYGUY_GREEN, $10, $18
	.byte OBJ_PARATROOPAGREENHOP, $15, $18
	.byte OBJ_SHYGUY_RED, $1F, $11
	.byte OBJ_PARATROOPAGREENHOP, $26, $18
	.byte OBJ_SHYGUY_GREEN, $27, $18
	.byte OBJ_SHYGUY_GREEN, $2C, $18
	.byte OBJ_SHYGUY_RED, $36, $15
	.byte OBJ_SHYGUY_GREEN, $3B, $10
	.byte OBJ_PARATROOPAGREENHOP, $3F, $10
	.byte OBJ_SHYGUY_RED, $5B, $12
	.byte OBJ_SHYGUY_RED, $5B, $18
	.byte OBJ_SHYGUY_RED, $5D, $15
	.byte OBJ_SHYGUY_GREEN, $68, $18
	.byte OBJ_SHYGUY_RED, $71, $10
	.byte OBJ_SHYGUY_GREEN, $74, $18
	.byte OBJ_PARATROOPAGREENHOP, $76, $18
	.byte OBJ_SHYGUY_GREEN, $82, $18
	.byte OBJ_SHYGUY_RED, $83, $10
	.byte OBJ_PARATROOPAGREENHOP, $84, $18
	.byte OBJ_FLYINGREDPARATROOPA, $9F, $01
	.byte OBJ_ALTLEVELMOD, $A0, $01
	.byte OBJ_TOUCHWARP, $A1, $00
	.byte $FF
