	.byte $00	; Unknown purpose

	.byte OBJ_ACTIONSWITCH, $00, $03
	.byte OBJ_CANCELEVENT, $05, $03
	.byte OBJ_PARABEETLESBEGIN, $16, $04
	.byte OBJ_PARABEETLESBEGIN, $36, $03
	.byte OBJ_CANCELEVENT, $41, $03
	.byte OBJ_GREENPIRANHA_FIRE, $50, $06
	.byte OBJ_PARATROOPAGREENHOP, $56, $17
	.byte OBJ_PARATROOPAGREENHOP, $59, $16
	.byte OBJ_PARATROOPAGREENHOP, $5C, $17
	.byte OBJ_SHYGUY_RED, $6A, $05
	.byte OBJ_SHYGUY_RED, $6C, $05
	.byte OBJ_CHECKPOINT, $76, $12
	.byte OBJ_GREENPIRANHA_FIRE_X, $7D, $04
	.byte OBJ_GREENPIRANHA_FIRE, $7F, $0B
	.byte OBJ_ENDLEVELCARD, $98, $10
	.byte $FF
