	.byte $00	; Unknown purpose

	.byte OBJ_PARABEETLE, $32, $08
	.byte OBJ_PARABEETLE, $38, $09
	.byte OBJ_PARABEETLE, $3D, $07
	.byte OBJ_PARABEETLE, $45, $09
	.byte OBJ_PARABEETLE, $4E, $09
	.byte OBJ_PARABEETLE, $53, $09
	.byte OBJ_PARABEETLE, $56, $06
	.byte OBJ_PARABEETLE, $73, $0B
	.byte OBJ_PARABEETLE, $73, $09
	.byte OBJ_PARABEETLE, $73, $0A
	.byte OBJ_PIRANHASPIKEBALL, $8C, $15
	.byte OBJ_PIRANHASPIKEBALL, $9B, $15
	.byte OBJ_PIRANHASPIKEBALL, $A3, $15
	.byte OBJ_PIRANHASPIKEBALL, $C3, $15
	.byte OBJ_PIRANHASPIKEBALL, $CD, $14
	.byte OBJ_SPIKE, $D1, $15
	.byte OBJ_PIRANHASPIKEBALL, $D9, $16
	.byte OBJ_REDTROOPA, $DB, $17
	.byte OBJ_PIRANHASPIKEBALL, $E2, $16
	.byte OBJ_REDTROOPA, $E5, $17
	.byte $FF
