	.byte $00	; Unknown purpose

	.byte OBJ_SHYGUY_RED, $09, $08
	.byte OBJ_FLYINGREDPARATROOPA, $17, $13
	.byte OBJ_FLYINGREDPARATROOPA, $19, $12
	.byte OBJ_FLYINGREDPARATROOPA, $1B, $13
	.byte OBJ_CHECKPOINT, $42, $18
	.byte OBJ_SPINY, $4B, $18
	.byte OBJ_SPINY, $4C, $18
	.byte OBJ_PARATROOPAGREENHOP, $4D, $18
	.byte OBJ_SPINY, $4E, $18
	.byte OBJ_FLYINGREDPARATROOPA, $62, $13
	.byte OBJ_FLYINGREDPARATROOPA, $6C, $13
	.byte OBJ_FLYINGREDPARATROOPA, $71, $13
	.byte OBJ_FLYINGREDPARATROOPA, $79, $13
	.byte OBJ_NIPPERFIREBREATHER, $7B, $15
	.byte OBJ_FLYINGREDPARATROOPA, $7D, $12
	.byte OBJ_SHYGUY_RED, $92, $16
	.byte OBJ_SHYGUY_RED, $95, $16
	.byte OBJ_ENDLEVELCARD, $B8, $02
	.byte $FF
