	.byte $00	; Unknown purpose

	.byte OBJ_GOBLIN, $0A, $13
	.byte OBJ_PARADRYBONES, $0F, $05
	.byte OBJ_PARADRYBONES, $19, $05
	.byte OBJ_PARADRYBONES, $23, $05
	.byte OBJ_GOBLIN, $2A, $0B
	.byte OBJ_CFIRE_MISSILEBILL, $40, $18
	.byte OBJ_CFIRE_MISSILEBILL, $4C, $15
	.byte OBJ_FIREJET_UPWARD, $76, $0C
	.byte OBJ_FIREJET_UPWARD, $7E, $0C
	.byte OBJ_FIREJET_UPWARD, $86, $0C
	.byte OBJ_FIREJET_UPWARD, $8E, $0C
	.byte $FF
