	.byte $00	; Unknown purpose

	.byte OBJ_GOOMBA, $0B, $16
	.byte OBJ_PARATROOPAGREENHOP, $2C, $14
	.byte OBJ_PARATROOPAGREENHOP, $31, $14
	.byte OBJ_VENUSFIRETRAP, $49, $17
	.byte OBJ_CHEEPCHEEPHOPPER, $5D, $17
	.byte OBJ_CHECKPOINT, $75, $16
	.byte OBJ_REDTROOPA, $78, $03
	.byte OBJ_REDTROOPA, $7C, $03
	.byte OBJ_GREENPIRANHA, $92, $15
	.byte OBJ_REDPIRANHA, $97, $12
	.byte OBJ_GREENPIRANHA, $9C, $14
	.byte OBJ_ENDLEVELCARD, $D6, $10
	.byte $FF
