	.byte $00	; Unknown purpose

	.byte OBJ_WOODENPLATUNSTABLE, $12, $18
	.byte OBJ_WOODENPLATUNSTABLE, $17, $14
	.byte OBJ_WOODENPLATUNSTABLE, $1F, $10
	.byte OBJ_FLYINGGREENPARATROOPA, $30, $10
	.byte OBJ_FLYINGREDPARATROOPA, $3E, $0F
	.byte OBJ_FLYINGGREENPARATROOPA, $47, $0F
	.byte OBJ_FLYINGREDPARATROOPA, $4F, $0E
	.byte OBJ_FLYINGGREENPARATROOPA, $59, $10
	.byte OBJ_FLYINGREDPARATROOPA, $6E, $0D
	.byte OBJ_FLYINGGREENPARATROOPA, $7A, $0D
	.byte OBJ_FLYINGREDPARATROOPA, $85, $10
	.byte OBJ_CHECKPOINT, $90, $18
	.byte OBJ_WOODENPLATFORMFALL, $AC, $10
	.byte OBJ_REDTROOPA, $BD, $0B
	.byte OBJ_REDTROOPA, $C4, $0F
	.byte OBJ_WOODENPLATFORMFALL, $CD, $0D
	.byte OBJ_WOODENPLATUNSTABLE, $CD, $16
	.byte $FF
