	.byte $00	; Unknown purpose

	.byte OBJ_REDTROOPA, $23, $12
	.byte OBJ_FLYINGREDPARATROOPA, $29, $11
	.byte OBJ_FLYINGGREENPARATROOPA, $53, $14
	.byte OBJ_REDTROOPA, $76, $15
	.byte OBJ_FLYINGREDPARATROOPA, $8B, $13
	.byte OBJ_FLYINGREDPARATROOPA, $99, $12
	.byte OBJ_CHECKPOINT, $9C, $17
	.byte OBJ_REDPIRANHA, $AB, $18
	.byte OBJ_REDPIRANHA, $B3, $18
	.byte OBJ_ENDLEVELCARD, $E7, $0D
	.byte $FF
