	.byte $00	; Unknown purpose

	.byte OBJ_FLYINGGREENPARATROOPA, $0B, $17
	.byte OBJ_FLYINGREDPARATROOPA, $16, $11
	.byte OBJ_FLYINGGREENPARATROOPA, $1F, $16
	.byte OBJ_FLYINGREDPARATROOPA, $28, $10
	.byte OBJ_FLYINGREDPARATROOPA, $2F, $12
	.byte OBJ_FLYINGREDPARATROOPA, $35, $0F
	.byte OBJ_FLYINGGREENPARATROOPA, $3A, $15
	.byte OBJ_FLYINGGREENPARATROOPA, $46, $14
	.byte OBJ_PARATROOPAGREENHOP, $59, $17
	.byte $FF
