	.byte $00	; Unknown purpose

	.byte OBJ_YOSHI, $15, $15
	.byte OBJ_GREENTROOPA, $20, $18
	.byte OBJ_GREENTROOPA, $26, $17
	.byte OBJ_GREENTROOPA, $2C, $16
	.byte OBJ_GREENTROOPA, $32, $18
	.byte OBJ_GREENTROOPA, $38, $16
	.byte OBJ_GREENTROOPA, $3F, $15
	.byte OBJ_GREENTROOPA, $47, $17
	.byte OBJ_GREENTROOPA, $4F, $19
	.byte OBJ_GREENTROOPA, $56, $17
	.byte OBJ_GREENTROOPA, $5D, $17
	.byte OBJ_GREENTROOPA, $62, $16
	.byte OBJ_GREENTROOPA, $67, $17
	.byte OBJ_GREENTROOPA, $6B, $15
	.byte OBJ_GREENTROOPA, $74, $18
	.byte OBJ_GREENTROOPA, $7B, $15
	.byte OBJ_GREENTROOPA, $83, $18
	.byte OBJ_GREENTROOPA, $87, $16
	.byte OBJ_CANCELEVENT, $8B, $10
	.byte OBJ_REDPIRANHA, $90, $16
	.byte OBJ_CHECKPOINT, $97, $17
	.byte OBJ_CFIRE_BULLETBILL, $98, $06
	.byte OBJ_CFIRE_BULLETBILL, $A9, $11
	.byte OBJ_CFIRE_BULLETBILL, $AB, $03
	.byte OBJ_BULLETBILLSBEGIN, $AE, $11
	.byte OBJ_CFIRE_BULLETBILL, $AE, $01
	.byte OBJ_CFIRE_BULLETBILL, $B9, $03
	.byte OBJ_CFIRE_BULLETBILL, $BD, $01
	.byte OBJ_BULLETBILLSBEGIN, $CB, $0E
	.byte OBJ_CANCELEVENT, $DD, $0E
	.byte OBJ_ENDLEVELCARD, $E8, $11
	.byte $FF
