	.byte $00	; Unknown purpose

	.byte OBJ_CLIMBINGKOOPA_G, $10, $14
	.byte OBJ_CLIMBINGKOOPA_G, $14, $13
	.byte OBJ_CLIMBINGKOOPA_R, $17, $11
	.byte OBJ_CLIMBINGKOOPA_GB, $1E, $15
	.byte OBJ_ALTLEVELMOD, $29, $00
	.byte OBJ_CLIMBINGKOOPA_GB, $2C, $15
	.byte OBJ_CLIMBINGKOOPA_R, $33, $13
	.byte OBJ_CLIMBINGKOOPA_GB, $37, $15
	.byte OBJ_CLIMBINGKOOPA_G, $3F, $13
	.byte OBJ_CLIMBINGKOOPA_R, $49, $16
	.byte OBJ_CLIMBINGKOOPA_GB, $4C, $16
	.byte OBJ_FENCE_CTL, $5C, $13
	.byte OBJ_CLIMBINGKOOPA_GB, $5C, $11
	.byte OBJ_CLIMBINGKOOPA_GB, $64, $13
	.byte OBJ_CLIMBINGKOOPA_GB, $66, $11
	.byte OBJ_FENCE_CTL, $6A, $15
	.byte OBJ_CLIMBINGKOOPA_R, $6E, $16
	.byte OBJ_ALTLEVELMOD, $6F, $00
	.byte OBJ_CLIMBINGKOOPA_RB, $77, $16
	.byte OBJ_FENCE_CTL, $79, $15
	.byte $FF
