	.byte $00	; Unknown purpose

	.byte OBJ_PARATROOPAGREENHOP, $2A, $17
	.byte OBJ_PARATROOPAGREENHOP, $2F, $17
	.byte OBJ_FLYINGREDPARATROOPA, $4F, $0F
	.byte OBJ_FLYINGREDPARATROOPA, $56, $0F
	.byte OBJ_FLYINGREDPARATROOPA, $66, $0F
	.byte OBJ_REDTROOPA, $89, $14
	.byte OBJ_CHECKPOINT, $8C, $16
	.byte OBJ_REDTROOPA, $94, $16
	.byte OBJ_REDTROOPA, $A0, $16
	.byte OBJ_GREENTROOPA, $BB, $12
	.byte OBJ_GREENTROOPA, $BE, $15
	.byte OBJ_GREENTROOPA, $C8, $11
	.byte OBJ_GREENTROOPA, $CB, $14
	.byte OBJ_PARATROOPAGREENHOP, $D0, $16
	.byte OBJ_PARATROOPAGREENHOP, $D5, $16
	.byte OBJ_PARATROOPAGREENHOP, $DB, $16
	.byte OBJ_ENDLEVELCARD, $E8, $10
	.byte $FF
