	.byte $00	; Unknown purpose

	.byte OBJ_CHECKPOINT, $09, $14
	.byte OBJ_REDTROOPA, $10, $10
	.byte OBJ_REDTROOPA, $20, $12
	.byte OBJ_REDTROOPA, $33, $14
	.byte OBJ_REDTROOPA, $38, $14
	.byte OBJ_BOOMERANGBRO, $45, $15
	.byte OBJ_BOOMERANGBRO, $4A, $15
	.byte OBJ_PARATROOPAGREENHOP, $5D, $11
	.byte OBJ_FLYINGGREENPARATROOPA, $62, $10
	.byte OBJ_PARATROOPAGREENHOP, $67, $11
	.byte OBJ_FLYINGREDPARATROOPA, $71, $0D
	.byte OBJ_PARATROOPAGREENHOP, $7D, $07
	.byte OBJ_PARATROOPAGREENHOP, $80, $09
	.byte OBJ_FLYINGGREENPARATROOPA, $88, $0C
	.byte OBJ_PARATROOPAGREENHOP, $9A, $16
	.byte OBJ_PARATROOPAGREENHOP, $9D, $15
	.byte OBJ_PARATROOPAGREENHOP, $A0, $14
	.byte OBJ_ENDLEVELCARD, $A7, $11
	.byte $FF
