	.byte $00	; Unknown purpose

	.byte OBJ_GREENPIRANHA, $1A, $08
	.byte OBJ_GREENPIRANHA, $20, $08
	.byte OBJ_VENUSFIRETRAP_CEIL, $3F, $07
	.byte OBJ_VENUSFIRETRAP_CEIL, $46, $07
	.byte OBJ_REDPIRANHA, $4F, $0E
	.byte OBJ_REDPIRANHA, $53, $0E
	.byte OBJ_REDPIRANHA, $57, $0E
	.byte OBJ_REDPIRANHA, $5B, $0E
	.byte OBJ_PIRANHASIDEWAYSLEFT, $79, $17
	.byte OBJ_PIRANHASIDEWAYSLEFT, $7B, $15
	.byte OBJ_PIRANHASIDEWAYSLEFT, $7F, $11
	.byte OBJ_PIRANHASIDEWAYSLEFT, $81, $0F
	.byte OBJ_CHECKPOINT, $93, $18
	.byte $FF
