	.byte $00	; Unknown purpose

	.byte OBJ_PIRANHASIDEWAYSRIGHT, $05, $11
	.byte OBJ_GREENPIRANHA, $07, $14
	.byte OBJ_GREENPIRANHA_FLIPPED, $07, $0F
	.byte OBJ_MUSICSET, $08, $40
	.byte OBJ_PIRANHASIDEWAYSLEFT, $0A, $11
	.byte OBJ_PIRANHASIDEWAYSRIGHT, $1D, $13
	.byte OBJ_PIRANHASIDEWAYSLEFT, $23, $15
	.byte OBJ_VENUSFIRETRAP, $34, $17
	.byte OBJ_VENUSFIRETRAP, $38, $16
	.byte OBJ_CHECKPOINT_FORCE, $49, $18
	.byte OBJ_ALTLEVELMOD, $4C, $14
	.byte $FF
