	.byte $00	; Unknown purpose

	.byte OBJ_PIRANHASIDEWAYSLEFT, $22, $09
	.byte OBJ_PIRANHASIDEWAYSLEFT, $22, $04
	.byte OBJ_PIRANHASIDEWAYSLEFT, $22, $0F
	.byte OBJ_WOODENPLAT_RIDER, $37, $19
	.byte OBJ_REDPIRANHA, $3C, $1A
	.byte OBJ_VENUSFIRETRAP_CEIL, $43, $13
	.byte OBJ_REDPIRANHA, $49, $1A
	.byte OBJ_GOOMBA, $4F, $10
	.byte OBJ_GOOMBA, $51, $10
	.byte OBJ_REDPIRANHA, $5B, $1A
	.byte OBJ_REDPIRANHA, $6B, $1A
	.byte OBJ_GOOMBA, $74, $11
	.byte OBJ_GOOMBA, $77, $11
	.byte OBJ_REDPIRANHA_FLIPPED, $8A, $13
	.byte OBJ_REDPIRANHA_FLIPPED, $8F, $13
	.byte OBJ_GREENPIRANHA, $99, $1A
	.byte OBJ_REDPIRANHA, $9A, $1A
	.byte OBJ_GREENPIRANHA, $9B, $1A
	.byte OBJ_GREENPIRANHA, $D5, $0C
	.byte OBJ_REDPIRANHA, $D9, $0A
	.byte OBJ_VENUSFIRETRAP, $DD, $08
	.byte $FF
