	.byte $00	; Unknown purpose

	.byte OBJ_CFIRE_GRAVITY_NORMAL, $02, $0A
	.byte OBJ_RREDTROOPA, $07, $11
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $11, $11
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $2A, $0E
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $32, $12
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $32, $0E
	.byte OBJ_REDTROOPA, $43, $0C
	.byte OBJ_RREDTROOPA, $43, $13
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $48, $0E
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $48, $12
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $53, $05
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $53, $0D
	.byte OBJ_GREENCHEEP, $53, $05
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $5C, $09
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $5C, $0D
	.byte OBJ_GREENCHEEP, $61, $0A
	.byte OBJ_LAUNCHSTAR, $7A, $08
	.byte $FF
