	.byte $00	; Unknown purpose

	.byte $00, $00, $00
	.byte OBJ_CHECKPOINT, $07, $06
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $09, $08
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $09, $09
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $11, $0F
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $11, $0E
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $1B, $14
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $1B, $13
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $24, $0D
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $24, $08
	.byte OBJ_VENUSFIRETRAP, $27, $04
	.byte OBJ_RBUZZYBEATLE, $2E, $0F
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $32, $0D
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $32, $08
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $33, $0D
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $37, $08
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $37, $0D
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $40, $17
	.byte OBJ_OCTOGOOMBA, $4E, $17
	.byte OBJ_OCTOGOOMBA, $55, $13
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $55, $0A
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $5D, $0A
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $8D, $14
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $95, $14
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $A5, $12
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $AD, $12
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $B5, $12
	.byte OBJ_ENDLEVELCARD, $B6, $10
	.byte $FF
