	.byte $00	; Unknown purpose

	.byte OBJ_BIGGREENHOPPER, $0B, $13
	.byte OBJ_BIGREDTROOPA, $14, $11
	.byte OBJ_BIGREDPIRANHA, $29, $19
	.byte OBJ_BIGREDPIRANHA, $30, $13
	.byte OBJ_BIGREDPIRANHA, $39, $19
	.byte OBJ_BIGGOOMBA, $3F, $17
	.byte OBJ_BIGGOOMBA, $41, $17
	.byte OBJ_BIGGOOMBA, $62, $07
	.byte OBJ_BIGGREENHOPPER, $68, $0F
	.byte OBJ_BIGGREENTROOPA, $88, $17
	.byte OBJ_BIGGREENTROOPA, $89, $0F
	.byte OBJ_BIGREDTROOPA, $8E, $07
	.byte OBJ_BIGGOOMBA, $9E, $17
	.byte OBJ_BIGGOOMBA, $A1, $17
	.byte OBJ_BIGGREENHOPPER, $AF, $0F
	.byte OBJ_BIGREDPIRANHA, $B1, $13
	.byte OBJ_BIGGOOMBA, $D4, $17
	.byte OBJ_BIGGOOMBA, $D7, $17
	.byte $FF
