	.byte $01	; Unknown purpose

	.byte OBJ_CHECKPOINT, $09, $18
	.byte OBJ_BIGGREENHOPPER, $1E, $15
	.byte OBJ_BIGREDPIRANHA, $41, $15
	.byte OBJ_BIGGOOMBA, $54, $17
	.byte OBJ_BIGGOOMBA, $57, $17
	.byte OBJ_BIGREDPIRANHA, $5F, $15
	.byte OBJ_BIGREDPIRANHA, $8A, $15
	.byte OBJ_BIGREDPIRANHA, $94, $0F
	.byte OBJ_BIGREDPIRANHA, $9B, $15
	.byte OBJ_BIGREDPIRANHA, $A3, $15
	.byte OBJ_BIGREDPIRANHA, $AB, $12
	.byte OBJ_BIGREDPIRANHA, $B3, $15
	.byte OBJ_BIGREDPIRANHA, $BD, $16
	.byte OBJ_BIGGREENTROOPA, $C6, $17
	.byte OBJ_BIGGREENTROOPA, $CA, $17
	.byte $FF
