	.byte $00	; Unknown purpose

	.byte OBJ_OCTOGOOMBA, $0F, $18
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $14, $11
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $1C, $13
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $1C, $10
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $24, $10
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $24, $13
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $2C, $13
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $2C, $10
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $34, $13
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $34, $10
	.byte OBJ_OCTOGOOMBA, $4C, $17
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $6C, $11
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $6C, $0A
	.byte OBJ_FIREJET_UPSIDEDOWN, $6F, $12
	.byte OBJ_FIREJET_UPWARD, $6F, $07
	.byte OBJ_FIREJET_UPWARD, $73, $07
	.byte OBJ_FIREJET_UPSIDEDOWN, $73, $12
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $77, $11
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $77, $0A
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $77, $0A
	.byte OBJ_FIRESNAKE, $92, $18
	.byte OBJ_CHECKPOINT, $AE, $11
	.byte OBJ_ICESNAKE, $C3, $17
	.byte $FF
