	.byte $00	; Unknown purpose

	.byte OBJ_CFIRE_GRAVITY_NORMAL, $0C, $0A
	.byte OBJ_BUZZYBEATLE, $0E, $0F
	.byte OBJ_BUZZYBEATLE, $11, $12
	.byte OBJ_BUZZYBEATLE, $13, $14
	.byte OBJ_BUZZYBEATLE, $15, $16
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $1B, $11
	.byte OBJ_REDPIRANHA_FLIPPED, $27, $10
	.byte OBJ_BUZZYBEATLE, $2C, $12
	.byte OBJ_GREENPIRANHA, $2D, $16
	.byte OBJ_RBUZZYBEATLE, $36, $07
	.byte OBJ_RREDTROOPA, $4A, $03
	.byte OBJ_RREDTROOPA, $56, $03
	.byte OBJ_RGREENTROOPA, $6C, $05
	.byte OBJ_VENUSFIRETRAP, $75, $15
	.byte OBJ_REDPIRANHA_FLIPPED, $7D, $14
	.byte $FF
