	.byte $00	; Unknown purpose

	.byte OBJ_CFIRE_GRAVITY_NORMAL, $02, $0F
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $02, $14
	.byte OBJ_CHECKPOINT, $0D, $0A
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $14, $14
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $14, $0F
	.byte OBJ_ICESNAKE, $1B, $10
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $1E, $14
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $1E, $0F
	.byte OBJ_ICESNAKE, $25, $0F
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $2A, $0F
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $2A, $14
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $32, $0F
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $32, $14
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $3A, $17
	.byte OBJ_OCTOGOOMBA, $59, $0A
	.byte OBJ_OCTOGOOMBA, $5F, $0C
	.byte OBJ_OCTOGOOMBA, $65, $0E
	.byte OBJ_OCTOGOOMBA, $6B, $10
	.byte $FF
