	.byte $00	; Unknown purpose

	.byte OBJ_CFIRE_GRAVITY_NORMAL, $03, $08
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $03, $0F
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $0C, $0B
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $0C, $0F
	.byte OBJ_RPARATROOPAGREENHOP, $10, $17
	.byte OBJ_GREENTROOPA, $28, $0B
	.byte OBJ_GREENTROOPA, $2A, $13
	.byte OBJ_ENDLEVELCARD, $67, $10
	.byte $FF
