	.byte $00	; Unknown purpose

	.byte OBJ_CFIRE_BULLETBILL, $0A, $0E
	.byte OBJ_TOPMAN, $0D, $16
	.byte OBJ_TOPMAN, $19, $12
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $2E, $0F
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $2E, $0D
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $35, $0D
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $35, $0F
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $3C, $0D
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $3C, $0F
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $43, $0F
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $43, $0D
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $4B, $10
	.byte OBJ_CFIRE_BULLETBILL, $54, $0A
	.byte OBJ_TOPMAN, $5C, $10
	.byte OBJ_TOPMAN, $63, $13
	.byte OBJ_TOPMAN, $6A, $0D
	.byte OBJ_CHECKPOINT, $71, $0D
	.byte OBJ_CFIRE_BULLETBILL, $72, $0E
	.byte OBJ_CFIRE_BULLETBILL, $7A, $10
	.byte OBJ_CFIRE_BULLETBILL, $7F, $0D
	.byte OBJ_TOPMAN, $8F, $10
	.byte OBJ_TOPMAN, $98, $11
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $9E, $12
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $9E, $0E
	.byte OBJ_TOPMAN, $A5, $0E
	.byte OBJ_TOPMAN, $AA, $0E
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $B2, $0E
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $B2, $12
	.byte OBJ_TOPMAN, $B7, $10
	.byte OBJ_ALTLEVELMOD, $BD, $17
	.byte $FF
