	.byte $00	; Unknown purpose

	.byte OBJ_CFIRE_GRAVITY_REVERSE, $05, $17
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $05, $15
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $0D, $10
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $0D, $13
	.byte OBJ_GREENCHEEP, $17, $13
	.byte OBJ_GREENCHEEP, $18, $0F
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $19, $13
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $19, $0F
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $24, $10
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $24, $13
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $2D, $14
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $2D, $07
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $38, $02
	.byte OBJ_RREDTROOPA, $3D, $17
	.byte OBJ_REDTROOPA, $3F, $05
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $42, $07
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $4A, $15
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $4A, $0F
	.byte OBJ_PODOBOO, $4F, $0B
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $55, $15
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $55, $0F
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $6A, $1A
	.byte OBJ_CHECKPOINT, $6A, $0E
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $71, $00
	.byte OBJ_RREDTROOPA, $77, $0D
	.byte OBJ_RREDTROOPA, $7C, $11
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $8E, $06
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $8E, $10
	.byte OBJ_GREENCHEEP, $8E, $10
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $99, $15
	.byte OBJ_FIRESNAKE, $A8, $14
	.byte OBJ_ENDLEVELCARD, $B8, $10
	.byte $FF
