	.byte $02	; Unknown purpose

	.byte OBJ_LAUNCHSTAR, $03, $0F
	.byte OBJ_OCTOGOOMBA, $07, $16
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $0E, $14
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $0E, $0B
	.byte OBJ_RBUZZYBEATLE, $1A, $18
	.byte OBJ_PARATROOPAGREENHOP, $21, $0A
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $24, $14
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $24, $0B
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $2C, $06
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $2C, $11
	.byte OBJ_GREENCHEEP, $33, $0D
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $34, $0D
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $34, $0A
	.byte OBJ_GREENCHEEP, $36, $0A
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $3C, $11
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $3C, $06
	.byte OBJ_CFIRE_GRAVITY_NORMAL, $44, $06
	.byte OBJ_CFIRE_GRAVITY_REVERSE, $66, $0B
	.byte $FF
