	.byte $00	; Unknown purpose

	.byte OBJ_SHYGUY_RED, $06, $13
	.byte OBJ_SHYGUY_RED, $0B, $0F
	.byte OBJ_FIREJET_UPSIDEDOWN, $0E, $09
	.byte OBJ_FIREJET_LEFT, $13, $0D
	.byte OBJ_CHECKPOINT, $20, $18
	.byte OBJ_SHYGUY_RED, $28, $14
	.byte OBJ_BOBOMBEXPLODE, $39, $18
	.byte OBJ_CFIRE_LBOBOMBS, $44, $11
	.byte OBJ_CFIRE_RBOBOMBS, $45, $11
	.byte OBJ_BOBOMBEXPLODE, $4F, $18
	.byte OBJ_CFIRE_LBOBOMBS, $4F, $0A
	.byte OBJ_CFIRE_RBOBOMBS, $50, $0A
	.byte OBJ_CFIRE_LBOBOMBS, $5D, $11
	.byte OBJ_CFIRE_RBOBOMBS, $5E, $11
	.byte OBJ_BOBOMBEXPLODE, $66, $18
	.byte OBJ_CHECKPOINT_FORCE, $6B, $17
	.byte $FF
