	.byte $00	; Unknown purpose

	.byte OBJ_FIREJET_RIGHT, $14, $0B
	.byte OBJ_FIREJET_RIGHT, $1B, $0D
	.byte OBJ_BOLTLIFT, $26, $0A
	.byte OBJ_FIREJET_UPWARD, $29, $0D
	.byte OBJ_FIREJET_UPWARD, $2C, $0D
	.byte OBJ_FIREJET_UPWARD, $2F, $0D
	.byte OBJ_CFIRE_URCANNON, $38, $11
	.byte OBJ_CFIRE_URCANNON, $3A, $11
	.byte OBJ_FIREJET_RIGHT, $49, $0A
	.byte OBJ_FIREJET_UPSIDEDOWN, $4A, $0E
	.byte OBJ_FIREJET_UPWARD, $62, $11
	.byte OBJ_FIREJET_RIGHT, $68, $10
	.byte OBJ_FIREJET_LEFT, $6A, $0D
	.byte OBJ_FIREJET_RIGHT, $6B, $0B
	.byte OBJ_CHECKPOINT, $72, $0B
	.byte OBJ_ROCKYWRENCH, $7E, $11
	.byte OBJ_FIREJET_RIGHT, $81, $10
	.byte OBJ_FIREJET_RIGHT, $89, $0F
	.byte OBJ_ROCKYWRENCH, $8D, $0B
	.byte OBJ_FIREJET_RIGHT, $90, $0A
	.byte OBJ_FIREJET_RIGHT, $97, $11
	.byte OBJ_BOLTLIFT, $99, $0E
	.byte OBJ_CFIRE_4WAY, $D6, $0C
	.byte OBJ_CFIRE_LLCANNON, $E7, $0B
	.byte OBJ_CHECKPOINT_FORCE, $E7, $18
	.byte OBJ_CFIRE_LLCANNON, $EC, $0B
	.byte $FF
