	.byte $00	; Unknown purpose

	.byte OBJ_ACTIONSWITCH, $00, $0A
	.byte OBJ_REDPIRANHA, $19, $08
	.byte OBJ_REDPIRANHA, $1B, $0B
	.byte OBJ_RREDTROOPA, $2C, $13
	.byte OBJ_RPARATROOPAGREENHOP, $39, $15
	.byte OBJ_REDPIRANHA_FLIPPED, $4C, $05
	.byte OBJ_RREDTROOPA, $4F, $06
	.byte OBJ_REDPIRANHA_FLIPPED, $50, $05
	.byte OBJ_VENUSFIRETRAP, $54, $0B
	.byte OBJ_VENUSFIRETRAP, $5B, $0B
	.byte OBJ_CHECKPOINT, $6C, $15
	.byte OBJ_ACTIONSWITCH, $6D, $0A
	.byte $FF
