	.byte $00	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $13
	.byte OBJ_FIREJET_UPSIDEDOWN, $17, $15
	.byte OBJ_FIREJET_UPSIDEDOWN, $1E, $15
	.byte OBJ_FIREJET_UPSIDEDOWN, $43, $14
	.byte OBJ_FIREJET_UPWARD, $43, $10
	.byte OBJ_CFIRE_LLCANNON, $54, $13
	.byte OBJ_CFIRE_LLCANNON, $57, $13
	.byte OBJ_CFIRE_LLCANNON, $66, $14
	.byte OBJ_CFIRE_LLCANNON, $67, $15
	.byte OBJ_CFIRE_LLCANNON, $6F, $13
	.byte OBJ_ROCKYWRENCH, $85, $16
	.byte OBJ_ROCKYWRENCH, $8B, $13
	.byte OBJ_PARATROOPAGREENHOP, $94, $14
	.byte OBJ_PARATROOPAGREENHOP, $9E, $15
	.byte OBJ_PARATROOPAGREENHOP, $A8, $13
	.byte OBJ_LAUNCHSTAR, $C6, $14
	.byte $FF
