	.byte $00	; Unknown purpose

	.byte OBJ_REDPIRANHA, $05, $0D
	.byte OBJ_REDPIRANHA, $09, $0D
	.byte OBJ_REDPIRANHA, $15, $0D
	.byte OBJ_REDPIRANHA, $19, $0D
	.byte OBJ_FLYINGREDPARATROOPA, $2E, $12
	.byte OBJ_FLYINGREDPARATROOPA, $3A, $12
	.byte OBJ_REDTROOPA, $50, $16
	.byte OBJ_FLYINGREDPARATROOPA, $56, $0F
	.byte OBJ_FLYINGREDPARATROOPA, $5B, $0F
	.byte OBJ_CHECKPOINT, $6C, $16
	.byte OBJ_REDPIRANHA_FLIPPED, $83, $0B
	.byte OBJ_REDPIRANHA_FLIPPED, $87, $0B
	.byte OBJ_GREENCHEEP, $95, $17
	.byte OBJ_FLYINGREDPARATROOPA, $AB, $12
	.byte OBJ_ENDLEVELCARD, $C9, $10
	.byte $FF
